# This is a basic workflow to help you get started with Actions

name: Automatic Release on Tag

# Controls when the workflow will run
on:
  # Triggers the workflow on tag creation to push out a release
  push:
    tags:
    - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      contents: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Make build script executable
        run: chmod +x .github/scripts/build.sh
          
      # Zip the deployment for distribution
      - name: Run build script
        run: .github/scripts/build.sh ${{ github.ref_name }} ${{ github.repository }}
      
      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release create --draft "${{ github.ref_name }}" --title "${{ github.ref_name }}" --generate-notes

      - name: Upload Template Files to Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release upload "${{ github.ref_name }}" "build/deploy.json" "build/createUiDefinition.json" "build/Templates/Arc SQL Single Pane of Glass.json" "build/Templates/SQL Licensing Summary.json"

  publish:
    name: Publish Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Publish Release
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: gh release edit "${{ github.ref_name }}" --draft=false
